use super::*;
use crate::SystemState;
use crate::displayed_item_tree::VisibleItemIndex;
use crate::message::{Message, MessageTarget};
use crate::table::sources::VirtualTableModel;
use crate::tests::snapshot::wait_for_waves_fully_loaded;
use crate::wave_container::VariableRef;
use crate::wave_container::VariableRefExt;
use crate::{StartupParams, WaveSource};
use project_root::get_project_root;
use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::AtomicBool;

mod analysis_and_filter_draft;
mod model_and_cache;
mod multi_signal;
mod scroll_columns;
mod selection_navigation_clipboard;
mod support;
mod transaction_trace;
