use ahash::AHashMap;
use eyre::Result;
use std::{
    cell::RefCell,
    collections::VecDeque,
    rc::Rc,
    sync::{Arc, atomic::AtomicBool},
};
use surfer_translation_types::translator::VariableNameInfo;
use tokio::task::JoinHandle;

use crate::{
    Channels, WcpClientCapabilities, command_prompt,
    file_history::FileHistory,
    hierarchy::{AllVariableCacheKey, ScopeExpandType, VariableListRow},
    message::Message,
    state::UserState,
    time::TimeInputState,
    translation::{TranslatorList, all_translators},
    wave_container::VariableRef,
    wave_source::{LoadOptions, LoadProgress},
};

pub(crate) type VariableInfoCache = AHashMap<VariableRef, Option<VariableNameInfo>>;

#[cfg(feature = "performance_plot")]
use crate::benchmark::Timing;
pub struct SystemState {
    pub user: UserState,
    pub(crate) layout_adapter: Option<crate::tiles::render::LayoutAdapter>,
    pub(crate) workspace_runtime: crate::tiles::runtime::WorkspaceRuntime,
    pub(crate) document_load_request: u64,
    pub(crate) pending_document: Option<crate::wave_source::PendingDocument>,
    pub(crate) file_history: FileHistory,
    /// Which translator to use for each variable
    pub(crate) translators: TranslatorList,
    /// Channels for messages generated by other threads
    pub channels: Channels,

    /// Tracks progress of file/variable loading operations.
    pub(crate) progress_tracker: Option<LoadProgress>,

    /// Buffer for the command input
    pub(crate) command_prompt: command_prompt::CommandPrompt,

    /// The context to egui, we need this to change the visual settings when the config is reloaded
    pub(crate) context: Option<Arc<egui::Context>>,

    /// List of batch messages which will executed as soon as possible
    pub(crate) batch_messages: VecDeque<Message>,
    pub(crate) batch_messages_completed: bool,

    /// The WCP server
    #[allow(unused)]
    pub(crate) wcp_server_thread: Option<JoinHandle<()>>,
    #[allow(unused)]
    pub(crate) wcp_server_address: Option<String>,
    #[allow(unused)]
    pub(crate) wcp_stop_signal: Arc<AtomicBool>,
    #[allow(unused)]
    pub(crate) wcp_running_signal: Arc<AtomicBool>,
    pub(crate) wcp_greeted_signal: Arc<AtomicBool>,
    pub(crate) wcp_client_capabilities: WcpClientCapabilities,

    /// The draw commands for every variable currently selected
    // For performance reasons, these need caching so we have them in a RefCell for interior
    // mutability
    pub(crate) variable_name_info_cache: RefCell<VariableInfoCache>,

    /// Monotonically increasing counter incremented when translators reload, to invalidate
    /// the `all_variable_rows_cache` when name info changes without a waveform reload.
    pub(crate) translator_generation: u64,
    /// Cached result of `build_variable_rows` for `draw_all_variables`; rebuilt only when the
    /// key changes (filter settings, wave data, or translator state).
    pub(crate) all_variable_rows_cache: Option<(AllVariableCacheKey, Rc<Vec<VariableListRow>>)>,

    // Egui requires a place to store text field content between frames
    pub(crate) url: RefCell<String>,
    pub(crate) command_prompt_text: RefCell<String>,
    pub(crate) surver_selected_file: RefCell<Option<usize>>,
    pub(crate) surver_load_options: RefCell<LoadOptions>,

    /// Character to add to the command prompt if it is visible.
    ///
    /// This is only needed for presentations at them moment.
    pub(crate) char_to_add_to_prompt: RefCell<Option<char>>,
    /// This item works with the expand scope feature to determine what hierarchys to open.
    pub scope_ref_to_expand: RefCell<Option<ScopeExpandType>>,

    pub(crate) time_widgets: RefCell<AHashMap<String, TimeInputState>>,
    /// Map of widget id -> focused state.
    pub(crate) text_edit_focused: AHashMap<String, bool>,
    /// Map of widget id -> one-shot request focus flag.
    pub(crate) text_edit_request_focus: AHashMap<String, bool>,
    // Benchmarking stuff
    /// Invalidate draw commands every frame to make performance comparison easier
    pub(crate) continuous_redraw: bool,
    #[cfg(feature = "performance_plot")]
    pub(crate) rendering_cpu_times: VecDeque<f32>,
    #[cfg(feature = "performance_plot")]
    pub(crate) timing: RefCell<Timing>,

    // Undo and Redo stacks
    pub(crate) undo_stack: Vec<crate::tiles::history::UndoRecord>,
    pub(crate) redo_stack: Vec<crate::tiles::history::UndoRecord>,

    // Toolbar group drag state
    pub(crate) toolbar_dragging_group: Option<String>,
    pub(crate) toolbar_drop_row: Option<usize>,
    pub(crate) toolbar_drop_index: Option<usize>,
    pub(crate) toolbar_drop_new_row: bool,

    pub(crate) url_callback: Option<Box<dyn Fn(String) -> Message + Send + 'static>>,

    // Only used for testing
    pub(crate) expand_parameter_section: bool,

    pub(crate) annotation_id_source: u64,
    pub(crate) click_handled: bool,
}

impl SystemState {
    pub fn new() -> Result<SystemState> {
        Self::new_inner(false)
    }

    #[cfg(test)]
    pub(crate) fn new_default_config() -> Result<SystemState> {
        Self::new_inner(true)
    }

    fn new_inner(force_default_config: bool) -> Result<SystemState> {
        let channels = Channels::new();
        let user = UserState::new(force_default_config)?;
        let file_history = FileHistory::load(user.config.behavior.file_history_size());

        // Basic translators that we can load quickly
        let translators = all_translators();

        let result = SystemState {
            user,
            file_history,
            translators,
            channels,
            progress_tracker: None,
            command_prompt: Default::default(),
            context: None,
            wcp_server_thread: None,
            wcp_server_address: None,
            wcp_stop_signal: Arc::new(AtomicBool::new(false)),
            wcp_running_signal: Arc::new(AtomicBool::new(false)),
            wcp_greeted_signal: Arc::new(AtomicBool::new(false)),
            wcp_client_capabilities: WcpClientCapabilities::new(),
            batch_messages: VecDeque::new(),
            batch_messages_completed: false,
            url: RefCell::new(String::new()),
            command_prompt_text: RefCell::new(String::new()),
            variable_name_info_cache: RefCell::new(AHashMap::new()),
            translator_generation: 0,
            layout_adapter: None,
            workspace_runtime: Default::default(),
            document_load_request: 0,
            pending_document: None,
            all_variable_rows_cache: None,

            char_to_add_to_prompt: RefCell::new(None),
            scope_ref_to_expand: RefCell::new(None),
            surver_selected_file: RefCell::new(None),
            surver_load_options: RefCell::new(LoadOptions::Clear),
            expand_parameter_section: false,
            time_widgets: RefCell::new(AHashMap::new()),
            text_edit_focused: AHashMap::new(),
            text_edit_request_focus: AHashMap::new(),
            url_callback: None,
            continuous_redraw: false,
            #[cfg(feature = "performance_plot")]
            rendering_cpu_times: VecDeque::new(),
            #[cfg(feature = "performance_plot")]
            timing: RefCell::new(Timing::new()),
            undo_stack: vec![],
            redo_stack: vec![],
            annotation_id_source: 0,
            click_handled: false,
            toolbar_dragging_group: None,
            toolbar_drop_row: None,
            toolbar_drop_index: None,
            toolbar_drop_new_row: false,
        };

        Ok(result)
    }
}

impl From<UserState> for SystemState {
    fn from(serializable_state: UserState) -> SystemState {
        let mut state = SystemState::new().unwrap();
        state.user = serializable_state;
        state
    }
}
