#!/usr/bin/env python3
"""Generate examples/kanata-wave.vcd for Konata/waveform time-axis sync tests.

The file mirrors examples/kanata-sample-2.ftr: the same 1 ns timescale and the
same 0..4542 ns time span, so that loading both files together exercises the
"Synchronize scroll" time-axis coupling between the waveform view and the
Konata pipeline view.

Signals (all in scope `tb`):
  - clk_fast     1-bit clock, 4 ns period
  - clk_slow     1-bit clock, 16 ns period
  - sine_a       real sine wave, 512 ns period, sampled every 4 ns
  - sine_b       real sine wave, 1514 ns period, sampled every 4 ns
  - counter      8-bit sawtooth counter, +1 every 4 ns (wraps at 256)
  - pwm          1-bit pulse-width signal, 64 ns period, 25% duty cycle
  - onehot       4-bit one-hot pattern rotating every 8 ns

Requires the pyvcd package (https://pypi.org/project/pyvcd/):
  pip install pyvcd
  python3 examples/kanata_wave_gen.py
"""

import math
from pathlib import Path

from vcd import VCDWriter

TIMESCALE = "1 ns"
END_TIME = 4542  # matches ftr_parser max_timestamp of kanata-sample-2.ftr
SAMPLE_PERIOD = 2  # ns between evaluation steps (clk_fast half-period)

OUT_PATH = Path(__file__).resolve().parent / "kanata-wave.vcd"


def main() -> None:
    with OUT_PATH.open("w") as f, VCDWriter(
        f,
        timescale=TIMESCALE,
        date="",  # keep the file byte-for-byte reproducible
        comment="Generated by examples/kanata_wave_gen.py",
    ) as writer:
        clk_fast = writer.register_var("tb", "clk_fast", "wire", size=1, init=0)
        clk_slow = writer.register_var("tb", "clk_slow", "wire", size=1, init=0)
        sine_a = writer.register_var("tb", "sine_a", "real", init=0.0)
        sine_b = writer.register_var("tb", "sine_b", "real", init=0.0)
        counter = writer.register_var("tb", "counter", "wire", size=8, init=0)
        pwm = writer.register_var("tb", "pwm", "wire", size=1, init=1)
        onehot = writer.register_var("tb", "onehot", "wire", size=4, init=1)

        for t in range(SAMPLE_PERIOD, END_TIME + 1, SAMPLE_PERIOD):
            writer.change(clk_fast, t, (t // 2) % 2)
            if t % 8 == 0:
                writer.change(clk_slow, t, (t // 8) % 2)
            if t % 4 == 0:
                writer.change(sine_a, t, math.sin(2.0 * math.pi * t / 512.0))
                writer.change(sine_b, t, math.sin(2.0 * math.pi * t / 1514.0))
                writer.change(counter, t, (t // 4) % 256)
            if t % 16 == 0:
                # 25% duty cycle over a 64 ns period.
                writer.change(pwm, t, 1 if t % 64 == 0 else 0)
            if t % 8 == 0:
                writer.change(onehot, t, 1 << ((t // 8) % 4))
        # The loop's last step lands exactly on END_TIME (clk_fast toggles
        # every 2 ns), so the VCD spans exactly the FTR duration.

    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
